services:
  app:
    build:
      context: app
      dockerfile: dockerfile
    restart: unless-stopped
    volumes:
      - ./app:/var/app
    env_file:
      - .env
    ports:
      - 8080:8080
    depends_on:
      - api

  api:
    build:
      context: api
      dockerfile: dockerfile
    restart: unless-stopped
    volumes:
      - ./api:/var/app
      - ./geoserver.d/data:/var/app/geoserver_data
    env_file:
      .env
    ports:
      - 8081:8080
    depends_on:
      - redis
      - geoserver

  redis:
    image: redis:latest
    container_name: redis
    restart: unless-stopped
    ports:
      - 6379:6379

  geoserver:
    image: docker.osgeo.org/geoserver:2.27.x
    container_name: geoserver
    restart: unless-stopped
    volumes:
      - ./geoserver.d/data:/opt/geoserver_data/data
      - ./geoserver.d/workspaces/RF-SITE-PLANNER:/opt/geoserver_data/workspaces/RF-SITE-PLANNER
    env_file:
      .env
    ports:
      - 8082:8080
