services:
  app:
    build:
      context: app
      dockerfile: dockerfile
    restart: unless-stopped
    volumes:
      - ./app:/var/app
    ports:
      - 8080:8080
    depends_on:
      - api

  api:
    build:
      context: api
      dockerfile: dockerfile
    restart: unless-stopped
    command: ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8080"]
    volumes:
      - ./api:/var/app
    ports:
      - 8081:8080
    depends_on:
      - redis

  redis:
    image: redis:latest
    container_name: redis
    restart: unless-stopped
    ports:
      - 6379:6379
