name: build-push-app-api

on:
  workflow_dispatch:
  push:

jobs:
  build-and-push:
    name: Build and Push App and API Images
    runs-on: ubuntu-latest
    environment: Production
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
          
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build APP
        uses: docker/build-push-action@v6
        with:
          context: app
          push: ${{ github.ref == 'refs/heads/main' }}
          tags: |
            ${{ vars.DOCKERHUB_USERNAME }}/rf-site-planner-app:latest
            ghcr.io/${{ github.repository_owner,, }}/rf-site-planner-app:latest

      - name: Build API
        uses: docker/build-push-action@v6
        with:
          context: api
          push: ${{ github.ref == 'refs/heads/main' }}
          tags: |
            ${{ vars.DOCKERHUB_USERNAME }}/rf-site-planner-api:latest
            ghcr.io/${{ github.repository_owner,, }}/rf-site-planner-api:latest
