name: build-push-app-api

on:
  workflow_dispatch:
  push:

permissions:
  contents: read
  packages: write

jobs:
  build-and-push:
    name: Build and Push App and API Images
    runs-on: ubuntu-latest
    environment: Production

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      # ========= APP =========
      - name: Build APP image (local)
        id: build-app
        uses: redhat-actions/buildah-build@v2
        with:
          context: app
          image: rf-site-planner-app
          tags: latest
          layers: true
          labels: |
            org.opencontainers.image.source=${{ github.server_url }}/${{ github.repository }}

      - name: Push APP to GHCR
        if: github.ref == 'refs/heads/main'
        uses: redhat-actions/push-to-registry@v2
        with:
          image: ${{ steps.build-app.outputs.image }}
          tags: ${{ steps.build-app.outputs.tags }}
          registry: ghcr.io/${{ github.repository_owner,, }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Push APP to Docker Hub
        if: github.ref == 'refs/heads/main'
        uses: redhat-actions/push-to-registry@v2
        with:
          image: ${{ vars.DOCKERHUB_USERNAME }}/rf-site-planner-app
          tags: ${{ steps.build-app.outputs.tags }}
          registry: docker.io
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # ========= API =========
      - name: Build API image (local)
        id: build-api
        uses: redhat-actions/buildah-build@v2
        with:
          context: api
          image: rf-site-planner-api
          tags: latest
          layers: true
          labels: |
            org.opencontainers.image.source=${{ github.server_url }}/${{ github.repository }}

      - name: Push API to GHCR
        if: github.ref == 'refs/heads/main'
        uses: redhat-actions/push-to-registry@v2
        with:
          image: ${{ steps.build-api.outputs.image }}
          tags: ${{ steps.build-api.outputs.tags }}
          registry: ghcr.io/${{ github.repository_owner,, }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Push API to Docker Hub
        if: github.ref == 'refs/heads/main'
        uses: redhat-actions/push-to-registry@v2
        with:
          image: ${{ vars.DOCKERHUB_USERNAME }}/rf-site-planner-api
          tags: ${{ steps.build-api.outputs.tags }}
          registry: docker.io
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
