name: build-push-splat-python

on:
  schedule:
    - cron: "0 0 * * 0"
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  build-and-push:
    name: Build and Push Splat Python Image
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
          
      - name: Build and Push Splat Python Image
        uses: docker/build-push-action@v6
        with:
          context: ./splat!
          push: true
          tags: ${{ vars.DOCKERHUB_USERNAME }}/splat-python:latest
          file: ./splat!/dockerfile
