name: ci

on:
  push:

jobs:
  build-app:
    name: Build APP
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version-file: app/package.json

      - name: Install dependencies
        run: yarn install
        working-directory: app

      - name: Build
        run: yarn build
        working-directory: app

  build-docker-images:
    name: Build Docker Images
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build APP
        uses: docker/build-push-action@v6
        with:
          context: app

      - name: Build API
        uses: docker/build-push-action@v6
        with:
          context: api
