name: docker

on:
  push:
    branches:
      - main

jobs:
  build-docker-images:
    name: Build Docker Images
    runs-on: ubuntu-latest
    environment: Production
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build APP
        uses: docker/build-push-action@v6
        with:
          context: app
          push: true
          tags: ${{ vars.DOCKERHUB_USERNAME }}/rf-site-planner-app:latest

      - name: Build API
        uses: docker/build-push-action@v6
        with:
          context: api
          push: true
          tags: ${{ vars.DOCKERHUB_USERNAME }}/rf-site-planner-api:latest
